name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: |
          curl -L -s -o /dev/null "https://f5cf6fijj9gm564r6aapt6.streamlit.app/"
